name: Build Project PDFs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-extra texlive-xetex

      - name: Build English PDF
        run: |
          # ROZWIĄZANIE: Używamy 'find' aby jawnie i niezawodnie znaleźć wszystkie pliki .md
          pandoc $(find docs/en -name "*.md") -o RUR_Project_Book_v1_en.pdf --toc --pdf-engine=xelatex

      - name: Build Polish PDF
        run: |
          # ROZWIĄZANIE: Używamy 'find' aby jawnie i niezawodnie znaleźć wszystkie pliki .md
          pandoc $(find docs/pl -name "*.md") -o RUR_Project_Book_v1_pl.pdf --toc --pdf-engine=xelatex
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RUR-Project-Books
          path: |
            RUR_Project_Book_v1_en.pdf
            RUR_Project_Book_v1_pl.pdf
