name: Build Project PDFs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Pandoc
        # ZMIANA: Zaktualizowano wersję z v1 na v4
        uses: pandoc/setup-pandoc@v4

      - name: Build English PDF
        run: |
          pandoc spec/en/*.md philosophy/en/*.md -o RUR_Project_Book_v1_en.pdf --toc --pdf-engine=xelatex

      - name: Build Polish PDF
        run: |
          pandoc spec/pl/*.md philosophy/pl/*.md -o RUR_Project_Book_v1_pl.pdf --toc --pdf-engine=xelatex
          
      - name: Upload English PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RUR-Project-Book-EN
          path: RUR_Project_Book_v1_en.pdf

      - name: Upload Polish PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RUR-Project-Book-PL
          path: RUR_Project_Book_v1_pl.pdf
          
